[workspace]
members = [
    "node",
    "runtime/stout",
    "runtime/trappist",
    "primitives/xcm",
]
exclude = [
    "contracts",
    "xcm-simulator"
]

[profile.release]
panic = "unwind"

[profile.production]
inherits = "release"
lto = true
codegen-units = 1
