[settings]
timeout = 1000

[relaychain]
chain = "rococo-local"
default_command = "../bin/9.37/polkadot"

  [[relaychain.nodes]]
  name = "alice"
  validator = true
  ws_port = 9900
  extra_args = [ "-lparachain=debug" ]

  [[relaychain.nodes]]
  name = "bob"
  validator = true
  extra_args = [ "-lparachain=debug" ]

  [[relaychain.nodes]]
  name = "charlie"
  validator = true
  extra_args = [ "-lparachain=debug" ]

  [[relaychain.nodes]]
  name = "david"
  validator = true
  extra_args = [ "-lparachain=debug" ]

[[parachains]]
id = 1836
add_to_genesis = true
cumulus_based = true

  [[parachains.collators]]
  name = "trappist-collator01"
  command = "./target/release/trappist-collator"
  ws_port = 9920
  args = ["--log=xcm=trace,pallet-assets=trace"]

  [[parachains.collators]]
  name = "trappist-collator02"
  command = "./target/release/trappist-collator"
  ws_port = 9921
  args = ["--log=xcm=trace,pallet-assets=trace"]

[[parachains]]
id = 3000
add_to_genesis = true
cumulus_based = true

  [[parachains.collators]]
  name = "stout-collator01"
  command = "./target_stout/release/stout-collator"
  ws_port = 9930
  args = ["--log=xcm=trace,pallet-assets=trace"]

  [[parachains.collators]]
  name = "stout-collator02"
  command = "./target_stout/release/stout-collator"
  ws_port = 9931
  args = ["--log=xcm=trace,pallet-assets=trace"]

[types.Header]
number = "u64"
parent_hash = "Hash"
post_state = "Hash"

[[hrmp_channels]]
sender = 2000
recipient = 3000
max_capacity = 8
max_message_size = 512

[[hrmp_channels]]
sender = 3000
recipient = 2000
max_capacity = 8
max_message_size = 512
