name: setup-worker
description: |
  This action sets up a worker for use in other actions. It installs the
  necessary dependencies for building the project.

runs:
  using: "composite"

  steps:
    - name: Setup Ubuntu dependencies
      shell: bash
      run: sudo apt update && sudo apt install -y git clang curl libssl-dev llvm libudev-dev cmake protobuf-compiler
